function Gc_vel_lin = jacobian_function_velocity_linearization(x_star, u_star, L, radius, len)
    phi_sym = x_star(4);

    % Extract elements from u_star
    fn_sym = u_star(1);
    ft_sym = u_star(2);
    phi_dot_sym = u_star(3);

    l1 = L(1,1);
    l2 = L(2,2);
    l3 = L(3,3);

    phi_val = x_star(4);

    if (phi_val >= 0 && phi_val < pi/4) || (phi_val >= 7*pi/4 && phi_val < 2*pi)
        Gc_vel_lin = [fn_sym*(2*l1*sin(2*phi_sym) - l3*radius*sin(2*phi_sym)*(2*radius*cos(2*phi_sym)^2 - 2*cos(2*phi_sym)*(len/2 + radius*cos(2*phi_sym))) ...
                 + 2*l3*radius*cos(2*phi_sym)*(sin(2*phi_sym)*(len/2 + radius*cos(2*phi_sym)) - radius*cos(2*phi_sym)*sin(2*phi_sym))) ...
                 + ft_sym*(2*l1*cos(2*phi_sym) + 2*l3*radius*cos(2*phi_sym)*(radius*sin(2*phi_sym)^2 + cos(2*phi_sym)*(len/2 + radius*cos(2*phi_sym))) ...
                 - l3*radius*sin(2*phi_sym)*(2*sin(2*phi_sym)*(len/2 + radius*cos(2*phi_sym)) - 2*radius*cos(2*phi_sym)*sin(2*phi_sym))) ...
                 - 4*phi_dot_sym*radius*cos(2*phi_sym), ...
                 l3*radius*sin(2*phi_sym)*(sin(2*phi_sym)*(len/2 + radius*cos(2*phi_sym)) - radius*cos(2*phi_sym)*sin(2*phi_sym)) - l1*cos(2*phi_sym), ...
                 l1*sin(2*phi_sym) + l3*radius*sin(2*phi_sym)*(radius*sin(2*phi_sym)^2 + cos(2*phi_sym)*(len/2 + radius*cos(2*phi_sym))), ...
                 -2*radius*sin(2*phi_sym);
                 
                 ft_sym*(2*l2*sin(2*phi_sym) - 2*l3*radius*cos(2*phi_sym)*(radius*sin(2*phi_sym)^2 + cos(2*phi_sym)*(len/2 + radius*cos(2*phi_sym))) ...
                 + l3*radius*sin(2*phi_sym)*(2*sin(2*phi_sym)*(len/2 + radius*cos(2*phi_sym)) - 2*radius*cos(2*phi_sym)*sin(2*phi_sym))) ...
                 - fn_sym*(2*l2*cos(2*phi_sym) - l3*radius*sin(2*phi_sym)*(2*radius*cos(2*phi_sym)^2 - 2*cos(2*phi_sym)*(len/2 + radius*cos(2*phi_sym))) ...
                 + 2*l3*radius*cos(2*phi_sym)*(sin(2*phi_sym)*(len/2 + radius*cos(2*phi_sym)) - radius*cos(2*phi_sym)*sin(2*phi_sym))) ...
                 - 4*phi_dot_sym*radius*sin(2*phi_sym), ...
                 - l2*sin(2*phi_sym) - l3*radius*sin(2*phi_sym)*(sin(2*phi_sym)*(len/2 + radius*cos(2*phi_sym)) - radius*cos(2*phi_sym)*sin(2*phi_sym)), ...
                 - l2*cos(2*phi_sym) - l3*radius*sin(2*phi_sym)*(radius*sin(2*phi_sym)^2 + cos(2*phi_sym)*(len/2 + radius*cos(2*phi_sym))), ...
                 2*radius*cos(2*phi_sym)];
    elseif phi_val >= pi/4 && phi_val < 3*pi/4
        Gc_vel_lin = [phi_dot_sym*radius*((2*cos(phi_sym))/sin(phi_sym) + (2*cos(phi_sym)^3)/sin(phi_sym)^3) - fn_sym*l3*radius^2 ...
                 - (fn_sym*l3*radius^2*cos(phi_sym)^2)/sin(phi_sym)^2, ...
                 (l3*radius^2*cos(phi_sym))/sin(phi_sym), ...
                 l3*radius^2 + l1, ...
                 -radius*(cos(phi_sym)^2/sin(phi_sym)^2 + 1);
                 
                 fn_sym*(l3*radius^2 + (l3*radius^2*cos(phi_sym)^2)/sin(phi_sym)^2), ...
                 - l2 - (l3*radius^2*cos(phi_sym))/sin(phi_sym), ...
                 -l3*radius^2, ...
                 0];
    elseif phi_val >= 3*pi/4 && phi_val < 5*pi/4
        Gc_vel_lin = [4*phi_dot_sym*radius*cos(2*phi_sym) - fn_sym*(2*l1*sin(2*phi_sym) + l3*radius*sin(2*phi_sym)*(4*radius*sin(2*phi_sym)^2 ...
                 - 2*radius*cos(2*phi_sym)^2 + 2*cos(2*phi_sym)*(len/2 - radius*cos(2*phi_sym))) + 2*l3*radius*cos(2*phi_sym)*(sin(2*phi_sym)*(len/2 - radius*cos(2*phi_sym)) ...
                 - radius*cos(2*phi_sym)*sin(2*phi_sym))) - ft_sym*(2*l1*cos(2*phi_sym) + 2*l3*radius*cos(2*phi_sym)*(radius*sin(2*phi_sym)^2 ...
                 + cos(2*phi_sym)*(len/2 - radius*cos(2*phi_sym))) - l3*radius*sin(2*phi_sym)*(2*sin(2*phi_sym)*(len/2 - radius*cos(2*phi_sym)) ...
                 - 6*radius*cos(2*phi_sym)*sin(2*phi_sym))), ...
                 l1*cos(2*phi_sym) - l3*radius*sin(2*phi_sym)*(sin(2*phi_sym)*(len/2 - radius*cos(2*phi_sym)) - radius*cos(2*phi_sym)*sin(2*phi_sym)), ...
                 - l1*sin(2*phi_sym) - l3*radius*sin(2*phi_sym)*(radius*sin(2*phi_sym)^2 + cos(2*phi_sym)*(len/2 - radius*cos(2*phi_sym))), ...
                 2*radius*sin(2*phi_sym);
                 
                 fn_sym*(2*l2*cos(2*phi_sym) + l3*radius*sin(2*phi_sym)*(4*radius*sin(2*phi_sym)^2 - 2*radius*cos(2*phi_sym)^2 ...
                 + 2*cos(2*phi_sym)*(len/2 - radius*cos(2*phi_sym))) + 2*l3*radius*cos(2*phi_sym)*(sin(2*phi_sym)*(len/2 - radius*cos(2*phi_sym)) ...
                 - radius*cos(2*phi_sym)*sin(2*phi_sym))) - ft_sym*(2*l2*sin(2*phi_sym) - 2*l3*radius*cos(2*phi_sym)*(radius*sin(2*phi_sym)^2 ...
                 + cos(2*phi_sym)*(len/2 - radius*cos(2*phi_sym))) + l3*radius*sin(2*phi_sym)*(2*sin(2*phi_sym)*(len/2 - radius*cos(2*phi_sym)) ...
                 - 6*radius*cos(2*phi_sym)*sin(2*phi_sym))) + 4*phi_dot_sym*radius*sin(2*phi_sym), ...
                 l2*sin(2*phi_sym) + l3*radius*sin(2*phi_sym)*(sin(2*phi_sym)*(len/2 - radius*cos(2*phi_sym)) - radius*cos(2*phi_sym)*sin(2*phi_sym)), ...
                 l2*cos(2*phi_sym) + l3*radius*sin(2*phi_sym)*(radius*sin(2*phi_sym)^2 + cos(2*phi_sym)*(len/2 - radius*cos(2*phi_sym))), ...
                 -2*radius*cos(2*phi_sym)];
    elseif phi_val >= 5*pi/4 && phi_val < 7*pi/4
        Gc_vel_lin = [fn_sym*l3*radius^2 - phi_dot_sym*radius*((2*cos(phi_sym))/sin(phi_sym) + (2*cos(phi_sym)^3)/sin(phi_sym)^3) + ...
                 (fn_sym*l3*radius^2*cos(phi_sym)^2)/sin(phi_sym)^2, ...
                 -(l3*radius^2*cos(phi_sym))/sin(phi_sym), ...
                 - l3*radius^2 - l1, ...
                 radius*(cos(phi_sym)^2/sin(phi_sym)^2 + 1);
                 
                 -fn_sym*(l3*radius^2 + (l3*radius^2*cos(phi_sym)^2)/sin(phi_sym)^2), ...
                 (l3*cos(phi_sym)*radius^2)/sin(phi_sym) + l2, ...
                 l3*radius^2, ...
                 0];
    end
end