
syms phi_sym fn_sym ft_sym phi_dot_sym L radius len l1 l2 l3
vec = [phi_sym; fn_sym; ft_sym; phi_dot_sym];

L = [l1 0 0; 0 l2 0; 0 0 l3];

% Define symbolic expressions for each case in the dynamics
dx_case1 = [(L(1,1)*(-cos(2*phi_sym))-L(3,3)*radius*sin(2*phi_sym)*(-radius*sin(2*phi_sym)*(-cos(2*phi_sym))+(len/2+radius*cos(2*phi_sym))*(-sin(2*phi_sym))))*fn_sym + ...
            (L(1,1)*(sin(2*phi_sym))-L(3,3)*radius*sin(2*phi_sym)*(-radius*sin(2*phi_sym)*(sin(2*phi_sym))+(len/2+radius*cos(2*phi_sym))*(-cos(2*phi_sym))))*ft_sym + ...
            (-2*radius*sin(2*phi_sym))*phi_dot_sym;

            (L(2,2)*(-sin(2*phi_sym))+L(3,3)*radius*sin(2*phi_sym)*(-radius*sin(2*phi_sym)*(-cos(2*phi_sym))+(len/2+radius*cos(2*phi_sym))*(-sin(2*phi_sym))))*fn_sym + ...
            (L(2,2)*(-cos(2*phi_sym))+L(3,3)*radius*sin(2*phi_sym)*(-radius*sin(2*phi_sym)*(sin(2*phi_sym))+(len/2+radius*cos(2*phi_sym))*(-cos(2*phi_sym))))*ft_sym + ...
            (2*radius*cos(2*phi_sym))*phi_dot_sym];
dx_case2 = [(L(1,1)*(0)-L(3,3)*radius*(-radius*(0)+(radius*(cos(phi_sym)/sin(phi_sym)))*(-1)))*fn_sym + ...
            (L(1,1)*(1)-L(3,3)*radius*(-radius*(1)+(radius*(cos(phi_sym)/sin(phi_sym)))*(0)))*ft_sym + ...
            (-radius*((cos(phi_sym)^2/sin(phi_sym)^2)+1))*phi_dot_sym;

            (L(2,2)*(-1)+L(3,3)*radius*(-radius*(0)+(radius*(cos(phi_sym)/sin(phi_sym)))*(-1)))*fn_sym + ...
            (L(2,2)*(0)+L(3,3)*radius*(-radius*(1)+(radius*(cos(phi_sym)/sin(phi_sym)))*(0)))*ft_sym + ...
            (0)*phi_dot_sym];
dx_case3 = [(L(1,1)*(cos(2*phi_sym))-L(3,3)*(-radius*sin(2*phi_sym))*(-(-radius*sin(2*phi_sym))*(cos(2*phi_sym))+(-len/2+radius*cos(2*phi_sym))*(sin(2*phi_sym))))*fn_sym + ...
            (L(1,1)*(-sin(2*phi_sym))-L(3,3)*(-radius*sin(2*phi_sym))*(-(-radius*sin(2*phi_sym))*(-sin(2*phi_sym))+(-len/2+radius*cos(2*phi_sym))*(cos(2*phi_sym))))*ft_sym + ...
            (2*radius*sin(2*phi_sym))*phi_dot_sym;

            (L(2,2)*(sin(2*phi_sym))+L(3,3)*(-radius*sin(2*phi_sym))*(-(-radius*sin(2*phi_sym))*(cos(2*phi_sym))+(-len/2+radius*cos(2*phi_sym))*(sin(2*phi_sym))))*fn_sym + ...
            (L(2,2)*(cos(2*phi_sym))+L(3,3)*(-radius*sin(2*phi_sym))*(-(-radius*sin(2*phi_sym))*(-sin(2*phi_sym))+(-len/2+radius*cos(2*phi_sym))*(cos(2*phi_sym))))*ft_sym + ...
            (-2*radius*cos(2*phi_sym))*phi_dot_sym];
dx_case4 = [(L(1,1)*(0)-L(3,3)*(-radius)*(radius*(0)+(-radius*(cos(phi_sym)/sin(phi_sym)))*(1)))*fn_sym + ...
            (L(1,1)*(-1)-L(3,3)*(-radius)*(radius*(-1)+(-radius*(cos(phi_sym)/sin(phi_sym)))*(0)))*ft_sym + ...
            (radius*((cos(phi_sym)^2/sin(phi_sym)^2)+1))*phi_dot_sym;

            (L(2,2)*(1)+L(3,3)*(-radius)*(radius*(0)+(-radius*(cos(phi_sym)/sin(phi_sym)))*(1)))*fn_sym + ...
            (L(2,2)*(0)+L(3,3)*(-radius)*(radius*(-1)+(-radius*(cos(phi_sym)/sin(phi_sym)))*(0)))*ft_sym + ...
            (0)*phi_dot_sym];

% Select the appropriate case based on phi value
phi_val = 3*pi/2;
if (phi_val >= 0 && phi_val < pi/4) || (phi_val >= 7*pi/4 && phi_val < 2*pi)
    f_sym = dx_case1;
elseif phi_val >= pi/4 && phi_val < 3*pi/4
    f_sym = dx_case2;
elseif phi_val >= 3*pi/4 && phi_val < 5*pi/4
    f_sym = dx_case3;
elseif phi_val >= 5*pi/4 && phi_val < 7*pi/4
    f_sym = dx_case4;
end

% Calculate the Jacobians of f_sym with respect to x and u
A = jacobian(f_sym, vec);



